In [1]:
import pandas as pd
#loads dataset into a numpy array and not as a dataframe
dataset=pd.read_csv('cardio_dataset.csv').values

In [5]:
print(dataset[:10])
print(dataset.shape)

[[  2.   48.  236.   66.    0.    2.    0.    1.1]
 [  1.   48.  260.   51.    0.    2.    1.    7. ]
 [  1.   44.  187.   49.    1.    2.    0.    7. ]
 [  2.   42.  216.   57.    1.    2.    0.    0.4]
 [  2.   56.  156.   42.    0.    2.    0.    2.2]
 [  1.   44.  162.   57.    1.    2.    0.    3. ]
 [  1.   50.  244.   47.    0.    2.    0.    4.2]
 [  1.   48.  212.   30.    1.    2.    0.   17.4]
 [  2.   66.  202.   53.    0.    2.    1.   13.4]
 [  1.   63.  186.   46.    1.    2.    0.   17.3]]
(6644, 8)


In [4]:
data=dataset[:,0:7]
target=dataset[:,7]
print(data.shape)
print(target.shape)

(6644, 7)
(6644,)


In [6]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.2)

In [7]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(train_data,train_target)

LinearRegression()

In [8]:
predicted_target=model.predict(test_data)

In [10]:
from sklearn.metrics import r2_score
r2=r2_score(test_target,predicted_target)
print("r2 score=",r2)

r2 score= 0.7498363676656565


In [11]:
#dataset needs preprocessing inorder to increase the r2 score

In [13]:
import joblib
joblib.dump(model,'regression_model.sav')

['regression_model.sav']